### PR TITLE
 Update rebar3 to 3.14.0-rc1 and relx to 4.0.0-rc1

### LINKED ISSUE #3225: Update rebar3 to 3.14.0-rc1 and relx to 4.0.0-rc1
For changes see:

https://github.com/erlware/relx/releases/tag/v4.0.0-rc1

https://github.com/erlang/rebar3/releases/tag/3.14.0-rc1

The release incorporate build speed improvements which drastically reduce release build times.

### PR DESCRIPTION
**Pull request by skkw**
Fixes #3225

### CODE REVIEW

**Comment by tolbrino** [comment]
Weird. Testing latest master the build time is:

```
$ time make local-build
real	8m42.374s
user	1m31.394s
sys	0m8.785s
```

Using this PR:
```
$ time make local-build
real	9m21.112s
user	1m49.313s
sys	0m10.671s
```

@tsloughter Is the new release expected to be slower?

**Comment by tsloughter** [comment]
Weird, no it is not. I suppose there is a chance it is slower for the initial build because it builds a more efficient structure for incremental builds /cc @ferd

When I tested on aeternity with an already compiled project the time to build the release was cut in half.

What all is "local-build" doing?

**Comment by tolbrino** [comment]
> What all is "local-build" doing?

It fetches all dependencies, builds the whole project, then builds a release.

**Comment by tolbrino** [comment]
@tsloughter The variance of build times of rocksdb might somehow mess with the overall build times though I guess.

**Comment by tolbrino** [comment]
@tsloughter Excluding rocksdb the builds are very similar in terms of build times. So no negative impact it seems.

**Comment by tsloughter** [comment]
Ok, good. The interesting part should come with incremental builds, both compiling and building releases.

**Comment by ferd** [comment]
Yeah, most of the compiler rework on my end may come at a slight disadvantage on the first build, but incremental ones should be much more limited and likely faster.

**Comment by zxq9** [comment]
Obsolete.

**Pull request closed without merging**
