### PR TITLE
Script basic deps license identification

### PR DESCRIPTION
**Pull request by lucafavatella**

### CODE REVIEW

**Comment by lucafavatella** [comment]
This is based on latest tag.

Please refer to commit messages (e.g. [this](https://github.com/aeternity/aeternity/pull/2529/commits/e56fb61e802ee6bb2ae7988f7607394d81c12ecc)) and contents (e.g. [this](https://github.com/aeternity/aeternity/pull/2529/commits/23b0acfb1d881dfd36803797804fd46b5ef5ef49)) for details.

**Comment by lucafavatella** [comment]
Items not inspected:
* Advanced native deps of rocksdb (snappy? lz4?)
* Other external deps: bucs, eper, ephemeral, exometer_core, gproc, hex2bin, lhttpc, lz4, sha3, aleppo.

**Comment by lucafavatella** [comment]
Depends on https://github.com/aeternity/docker-builder/pull/21

**Comment by sennui** [comment]
There is also cuckoo with its dual gpl2 and fair mining license

**Pull request closed without merging**
