### PR TITLE
Aesophia rebar plugin

### PR DESCRIPTION
**Pull request by gorbak25**
This PR adds a rebar plugin for interacting with the sophia compiler when building the node.
This will be used in the build system of hyperchains.

The plugin introduces 2 neat operations:
- Compile and generate the ACI:
```
./rebar3 aesophia -c contract.aes -o result.json
```
- Verify the contract bytecode:
```
./rebar3 aesophia -c contract.aes -o result.json -v
```

### CODE REVIEW

**Review by hanssv — COMMENTED** [review]
Does the plugin have a dependency on a compiler? If so, this should be a test dependency (is there such a thing for a plugin?)?

**Comment by gorbak25** [comment]
@hanssv 
The plugin depends on aesophia_cli. 
I've checked that in the final release plugins are stripped away - the plugin is meant only to be used in the build process. 
Plugin dependencies are kept separate from the normal dependencies.

**Comment by hanssv** [comment]
The build process of the normal node should _not_ depend on the compiler...

**Review by radrow — APPROVED** [review]

**Review by erlmachinedev — APPROVED** [review]

**Review by hanssv — COMMENTED** [review]
This is the Aeternity node? Surely the HyperChains node will be a separate thing?

**Comment by hanssv** [comment]
For the Hyperchain node it sounds reasonable, but I can't see why it wouldn't be sufficient to just have that fixed version of `aesophia_cli` as a dependency and just do `aesophia_cli ...` instead of going through `rebar3` - though I am perhaps overly negative about `rebar3`, it isn't on my Xmas card list 😄

**Pull request merged**
