### PR TITLE
Force community fork

### PR DESCRIPTION
**Pull request by gorbak25**
Force the node on the community fork

### CODE REVIEW

**Review by velzevur — DISMISSED** [review]

**Review by velzevur — DISMISSED** [review]

**Review by radrow — APPROVED** [review]
bye bye 51 <3

**Comment by gorbak25** [comment]
Started to test the build:
https://builds.aeternity.io/aeternity-a991b3ff52ec09503be9532beb3a4148deefaa0c-ubuntu-x86_64.tar.gz

**Comment by gorbak25** [comment]
Test deploy worked, node operates nominally. Starting to test more intresting cases.

**Review by velzevur — APPROVED** [review]

**Review by erlmachinedev — APPROVED** [review]

**Review by radrow — APPROVED** [review]

**Review by erlmachinedev — DISMISSED** [review]

**Review by velzevur — DISMISSED** [review]

**Comment by gorbak25** [comment]
Take 2 at https://builds.aeternity.io/aeternity-77070ff526715af63f8b64f362d8e2caf0b07060-ubuntu-x86_64.tar.gz

**Review by erlmachinedev — APPROVED** [review]

**Review by velzevur — DISMISSED** [review]

**Comment by gorbak25** [comment]
Take 3 at https://builds.aeternity.io/aeternity-bb882df502fbfe1838cf8b7c2156a2624e64a2b4-ubuntu-x86_64.tar.gz

**Review by erlmachinedev — DISMISSED** [review]

**Review by velzevur — APPROVED** [review]

**Comment by gorbak25** [comment]
Take 4 at https://builds.aeternity.io/aeternity-8722ccb426c6c9c4ac1ead3c041f19d1b5564f3d-ubuntu-x86_64.tar.gz

**Review by erlmachinedev — APPROVED** [review]

**Review by erlmachinedev — APPROVED** [review]

**Comment by gorbak25** [comment]
Take 5 at  https://builds.aeternity.io/aeternity-1e8940390852f3f286b4eaa1112ef640423bf3b7-ubuntu-x86_64.tar.gz

**Review by erlmachinedev — DISMISSED** [review]

**Review by velzevur — APPROVED** [review]

**Comment by gorbak25** [comment]
Take 6 at  https://builds.aeternity.io/aeternity-bf644a2577aa9852a1c0bb51f1b9e79906f01a25-ubuntu-x86_64.tar.gz

**Review by erlmachinedev — APPROVED** [review]

**Review by velzevur — DISMISSED** [review]

**Comment by gorbak25** [comment]
Take 8 at  https://builds.aeternity.io/aeternity-2b9d98218d39495b28582de7d582e7c523905f49-ubuntu-x86_64.tar.gz

**Review by erlmachinedev — APPROVED** [review]

**Comment by gorbak25** [comment]
Take 8 at https://builds.aeternity.io/aeternity-f6983394ff4e5f001a3e48447b08a4dcf730fd1a-ubuntu-x86_64.tar.gz

**Comment by gorbak25** [comment]
Rollback finally works on 9a - a node jumped from the attacker's chain to the community fork!
Bugs: aehttp fails to start on the first bootup

**Comment by gorbak25** [comment]
Take 9b at: https://builds.aeternity.io/aeternity-275bc0e9012a22a29037331a6b814fcc0f3f9012-ubuntu-x86_64.tar.gz

**Comment by gorbak25** [comment]
take 9b does not work at all

**Review by erlmachinedev — DISMISSED** [review]

**Review by erlmachinedev — APPROVED** [review]

**Review by velzevur — APPROVED** [review]

**Comment by gorbak25** [comment]
Take 10 at  https://builds.aeternity.io/aeternity-395887d71bfa805eae9792a7b53ac47c0e2f9385-ubuntu-x86_64.tar.gz

**Comment by gorbak25** [comment]
Take 10 - no hiccups so far - the main functionality works as intended. More testing and a canary deployment will follow soon

**Pull request merged**
