### PR TITLE
Bundle package

### PR DESCRIPTION
**Pull request by dincho**
Create a bundle package that includes aeplugin_dev_mode (should include all in future). The package is with suffix "-bundle", I'm open for better ideas.

TODO:
- [x] remove test docker image push job

### CODE REVIEW

**Comment by marc0olo** [comment]
seems to look good to me in general. are you planning to bundle and publish the image with every release?

**Review by velzevur — DISMISSED** [review]

**Comment by dincho** [comment]
> seems to look good to me in general. are you planning to bundle and publish the image with every release?

yes, also with every master the names would be:

`aeternity/aeternity:v6.3.0-bundle` and `aeternity/aeternity:master-bundle`

**Review by marc0olo — APPROVED** [review]

**Review by velzevur — APPROVED** [review]

**Review by uwiger — APPROVED** [review]
LGTM

**Comment by marc0olo** [comment]
@dincho is it desired to still have the docker test push job as you marked this as todo? or did you forget to rename?

**Comment by dincho** [comment]
> @dincho is it desired to still have the docker test push job as you marked this as todo? or did you forget to rename?

that's the original name of the job for some reason 🤷🏻

**Review by marc0olo — APPROVED** [review]

**Pull request merged**
