### PR TITLE
Add whitelisting extension script

### PR DESCRIPTION
**Pull request by uwiger**
See issue #3467

The script is designed so that it can be run separately, e.g. by simply downloading the `aeutils/priv/create_whitelist` file and calling it as a normal escript. In this case, connect parameters must be explicitly provided.

Example:

```
~/test$ escript ~/ae/3/aeternity/apps/aeutils/priv/create_whitelist -sname aeternity@localhost -setcookie aeternity_cookie -start 100 -n 10 -step 10 -o mywhitelist.json
Writing to file: mywhitelist.json

~/test$ cat mywhitelist.json 
{
  "48278": "kh_2mUakNK4UuFHsgBFkVTUQu7h1pAeDFwMh5DzzbPwAAnJ6SrnjK",
  "48288": "kh_wPNz6CHSgnPSP6mMPhDuidSCrcuRSAPkQQwdYAeQzC4h5GLao",
  "48298": "kh_D6cRdye4Ffvmze26Dgq1bVtdnRbcHmbjLsFY3FqTsLgbhMDvj",
  "48308": "kh_27G4Jsejy2CqBvZvuCbprJah8eyncLJ6Q3eqkxe6KvpUqEKAzW",
  "48318": "kh_2nDQ4VT7YGXT3ktvdVV4w1cHNF6Rqe642xyALbTzzubHyAHSQm",
  "48328": "kh_2uEqQq4N8He966t4uoMWe4VxtgwKSU8ZW9NC3AHpQ6y3SkVrFa",
  "48338": "kh_2sXTdrKnLQCAdpUzeYoXczNDNvkjzdhUhhzfHVzTyiLFxAygKj",
  "48348": "kh_8QFcgn3yC25sFtikbJqXbXNe9P4ww8ELMXs6MwTRobugPEbkR",
  "48358": "kh_28wxVJzXyCXJUJdayHTwtUtyGytRSw8zeCRjRHexj3bnXde4MC",
  "48368": "kh_2UhGTzeNiiz5VLkzEXmL5QxjMBJUgBkKsp24tjZLEVFkbUXWo5"
}
```

The script currently doesn't provide a help text. The idea is:
* Start `<start>` blocks below the current top
* Collect `<n>` hashes from, and including, the `<start>` height, `<step>` steps apart
* Convert to JSON and write to the filename provided with `-o`. Default is a temporary file in the current directory

In order to prevent against long-range attacks, the whitelist should go at least 1000 or so blocks deep. The whitelisted blocks shouldn't be too far apart, since an attacker with enormous hash power could bump the difficulty with relatively few blocks (esp. if the current chain has very low hash power).

If this script is called periodically from a wrapper script that also exports a config variable, `AE__SYNC__WHITELIST_FILE` to the generated file, it could provide a short-term protection against fork injection attacks. PR #3486 should give stronger protection once merged.

The work on this PR is supported by the Aeternity Crypto Foundation.

### CODE REVIEW

**Comment by uwiger** [comment]
Note: The whitelist file name isn't configurable until release 5.6.4. On earlier releases (5.6.2, 5.6.3), the `data/aecore/.block_whitelist.json` file would need to be replaced.

**Comment by uwiger** [comment]
Rebased against current master

**Review by gorbak25 — APPROVED** [review]
If you are already on a wrong fork then this script won't help you at all :P

**Comment by uwiger** [comment]
> If you are already on a wrong fork then this script won't help you at all :P

Unless some helpful soul who _is_ on the right fork uses it to create a whitelist that you can install. :P

**Comment by dincho** [comment]
I'd suggest adding -o stdout and make it default if that's not much work

**Comment by uwiger** [comment]
A whitelisting extension script was added as part of PR #3704
Closing

**Pull request closed without merging**
