### PR TITLE
Update aesophia_cli to 4.3.1

### PR DESCRIPTION
**Pull request by radrow**

### CODE REVIEW

**Comment by radrow** [comment]
What the hell
```
Failure/Error: {error,
                        {badmatch,
                            {error,
                                {compiler_error,
                                    "/home/builder/aeternity/_build/test/lib/aecontract/../../extras/test/contracts/identity.aes",
                                    <<"Compiler error:\nescript: exception error: undefined function aesophia_cli:main/1\n
```

**Comment by tolbrino** [comment]
Release notes missing.

**Comment by hanssv** [comment]
Well, the binary checked into priv/bin/v4.3.0 in aesophia_cli is broken 🤷‍♂️

**Comment by hanssv** [comment]
There is no need for release notes, this is just updating the internal tests.

**Pull request merged**
