### PR TITLE
Pt 165173618 break out aeprimops

### PR DESCRIPTION
**Pull request by gorillainduction**
https://www.pivotaltracker.com/story/show/165173618

### CODE REVIEW

**Comment by lucafavatella** [comment]
Conflicts, marking as WIP.

**Comment by gorillainduction** [comment]
Rebased on master to get generalized accounts.

**Comment by gorillainduction** [comment]
Fixed some rebase errors

**Comment by gorillainduction** [comment]
And another rebase on master to resolve conflicts

**Comment by gorillainduction** [comment]
Rerunning tests on known shaky test cases

**Pull request merged**
