### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by velzevur**
This improves stability of the CI,, fixes issues like:
```
%%% aecore_sync_SUITE ==> all_nodes.performance.persistence.trusted_peer_is_untrusted_after_a_restart: FAILED
%%% aecore_sync_SUITE ==> {{badmatch,0},
 [{aecore_sync_SUITE,trusted_peer_is_untrusted_after_a_restart,1,
                     [{file,"/home/builder/aeternity/apps/aecore/test/aecore_sync_SUITE.erl"},
                      {line,970}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
```

The work on this PR is supported by the Aeternity Crypto Foundation.

### CODE REVIEW

**Comment by velzevur** [comment]
Tests had passed. Restarting them.

**Comment by velzevur** [comment]
Tests failed with 
```
%%% aecore_sync_SUITE ==> {{badmatch,{[#{host => <<"127.0.0.1">>,port => 4714,
               pubkey =>
                   <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                     0,1,44,40>>},
             #{host => <<"127.0.0.1">>,port => 4723,
               pubkey =>
                   <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                     0,16,40,43>>},
             #{host => <<"127.0.0.1">>,port => 4899,
               pubkey =>
                   <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                     0,2,93,232>>}],
            [#{host => <<"127.0.0.1">>,port => 4714,
               pubkey =>
                   <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                     0,1,44,40>>},
             #{host => <<"127.0.0.1">>,port => 4723,
               pubkey =>
                   <<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                     0,0,16,40,43>>}]}},
 [{aecore_sync_SUITE,assert_available_peers,2,
                     [{file,"/home/builder/aeternity/apps/aecore/test/aecore_sync_SUITE.erl"},
                      {line,1145}]},
  {aecore_sync_SUITE,add_and_delete_untrusted_peers_and_restart,1,
                     [{file,"/home/builder/aeternity/apps/aecore/test/aecore_sync_SUITE.erl"},
                      {line,900}]},

**Comment by velzevur** [comment]
Tests failed with
```

%%% aestratum_integration_SUITE ==> {test_case_failed,
    {retry_exhausted,
        #{info =>
              {535,await_block,dev1,
               {key_block,
                   {key_header,5,
                       <<51,36,209,87,13,69,100,223,189,168,202,214,166,50,228,
                         247,245,220,250,253,210,29,57,101,118,110,39,119,166,
                         118,247,180>>,
                       <<51,36,209,87,13,69,100,223,189,168,202,214,166,50,228,
                         247,245,220,250,253,210,29,57,101,118,110,39,119,166,
                         118,247,180>>,
                       <<78,153,74,185,219,16,188,120,67,79,203,6,15,209,177,
                         201,1,81,164,172,196,226,53,228,103,61,178,12,225,100,
                         215,6>>,
                       553713663,16336050089969285694,1606830640153,3,
                       [1272,1930,3394,3730,4326,4483,6996,10973,12892,13858,
                        14153,15160,16120,16139,16826,17232,17250,18399,18776,
                        19034,19735,19968,20784,21233,21708,21975,22731,22792,
                        22968,25629,26011,26156,27015,28338,28376,29069,29837,
                        30217,30777,30815,31497,31836],
                       <<211,23,244,163,166,7,42,186,95,5,109,88,175,88,215,
                         175,56,69,90,231,88,250,127,186,191,0,172,22,176,166,
                         162,181>>,
                       <<196,91,250,26,142,128,101,175,167,63,59,140,213,136,
                         18,246,178,144,206,232,21,159,79,56,238,56,193,185,11,
                         55,15,127>>,
                       <<0,0,2,43>>,
                       #{}}}},
          prev => undefined,retries => 10,tries => 0}}}

%%% aestratum_integration_SUITE ==> all.single_client.rewarding_participants: SKIPPED
```
Which is unrelated to this PR, restarting them to check if any of the sync-related issues would appear again

**Comment by velzevur** [comment]
Tests passed happily, restarting all tests again for the last time.

**Review by uwiger — APPROVED** [review]

**Review by gorbak25 — APPROVED** [review]

**Pull request merged**
