### PR TITLE
Hint how to create lib links on macOS

### PR DESCRIPTION
**Pull request by lucafavatella**
I am using this snippet locally and I wonder if it would be of use to users.

### CODE REVIEW

**Comment by nikita-fuchs** [comment]
Nice idea, but I'm getting `zsh: parse error: condition expected: = `

**Comment by dincho** [comment]
> Nice idea, but I'm getting `zsh: parse error: condition expected: =`

It's bash.

@lucafavatella perhaps drop a row that the examples are for `bash`

**Comment by dincho** [comment]
Hmm, similar issue in bash ?!

```
$ test $(readlink /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib) = "$(brew --prefix openssl)"/lib/libcrypto.1.0.0.dylib || echo WARNING: Run: ln -s "$(brew --prefix openssl)"/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
-bash: test: =: unary operator expected
WARNING: Run: ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
```

**Comment by lucafavatella** [comment]
> Hmm, similar issue in bash ?!

@dincho Reproduced in bash, I pushed fix.

@nikita-fuchs Could you please retest?

**Comment by nikita-fuchs** [comment]
@lucafavatella command doesn't throw error anymore, but getting this confusing recommendation:

`WARNING: Run: ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib`

**Comment by dincho** [comment]
> @lucafavatella command doesn't throw error anymore, but getting this confusing recommendation:
> 
> `WARNING: Run: ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib`

Same on my side:

```
$ test "$(readlink /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib)" = "$(brew --prefix openssl)"/lib/libcrypto.1.0.0.dylib || echo WARNING: Run: ln -s "$(brew --prefix openssl)"/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
WARNING: Run: ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
```

**Comment by lucafavatella** [comment]
@dincho @nikita-fuchs That paragraph was specifically for homebrew installation in non-default path ("In case you have installed either of them in a non-default path") but if it confused you then better to make the documentation less smart.

We can either include the simple hint on how to create links (as in this PR) or simply reject this PR.

**Pull request merged**
