### PR TITLE
GH 3151 AEVM deprecation and cleanup

### PR DESCRIPTION
**Pull request by hanssv**
~~The remaining question/problem is with FATE cross VM calls. There are several options, fixing it, do nothing, or, allow FATE VM1 contracts to be created also on IRIS.~~

This PR is supported by the Æternity Crypto Foundation

### CODE REVIEW

**Review by gorbak25 — CHANGES_REQUESTED** [review]
Fate interoperability is provided via: https://github.com/aeternity/aeternity/pull/3540

**Comment by cytadela8** [comment]
This will be good without `Disallow cross VM calls for FATE`

**Comment by hanssv** [comment]
Removed the no longer needed fixup's and tests for FATE, this now just stops the creation of AEVM contracts in Iris and updates the AEVM interoperability tests accordingly.

**Review by cytadela8 — DISMISSED** [review]

**Review by cytadela8 — APPROVED** [review]

**Review by velzevur — APPROVED** [review]
LGTM

**Review by gorbak25 — APPROVED** [review]

**Pull request merged**
