### PR TITLE
GH 2964 SC: tighten up checks

### LINKED ISSUE #2964: Tighten up checks regarding participants of close solo and FP
Improve tests and add a few checks

### PR DESCRIPTION
**Pull request by velzevur**
Fixes #2964

### CODE REVIEW

**Comment by hanssv** [comment]
A couple of warnings, not sure they are new:
```
apps/aechannel/test/aesc_txs_SUITE.erl:3060: Warning: variable 'Forcer' is unused
apps/aechannel/test/aesc_txs_SUITE.erl:4869: Warning: function negative_close_solo_with_optional_payload/2 is unused
```

**Comment by velzevur** [comment]
@hanssv they are new, Fixing those

**Comment by tolbrino** [comment]
@velzevur This can be closed since the lima branch will be merged to master incl. this change.

**Comment by velzevur** [comment]
Fixed in #2964

**Pull request closed without merging**
