### PR TITLE
HC-C tidying up and fixes

### PR DESCRIPTION
**Pull request by rustaem**
Generic fixes and tidying up. R20 stacktrace in catches, some unused names, dismatches.

### CODE REVIEW

**Comment by cytadela8** [comment]
Looks good, I changed the base and removed comment lines. btw. You can push your branches directly to aeternity/aeternity. Do you not have permissions?

**Comment by cytadela8** [comment]
You could also backport the fixes not relevant to hyperchains for master in a separate PR

**Comment by rustaem** [comment]
> Looks good, I changed the base and removed comment lines. btw. You can push your branches directly to aeternity/aeternity. Do you not have permissions?

God no, please no exp permissions for the onboarding phase.

**Comment by cytadela8** [comment]
We also need a rebase here!

**Comment by cytadela8** [comment]
Chnages themselve are ready :)

**Comment by cytadela8** [comment]
Please rebase not merge. This creates unnecessery mess. Consider reading following interesting articles:

- https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase
- https://www.atlassian.com/git/tutorials/merging-vs-rebasing
- https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by rustaem** [comment]
> Please rebase not merge.

Sorry, was attempting to ease your part.

**Pull request merged**
