### PR TITLE
GH 3501:  aecore txs failures

### PR DESCRIPTION
**Pull request by velzevur**
Improves #3501

### CODE REVIEW

**Review by gorbak25 — APPROVED** [review]

**Comment by velzevur** [comment]
Tests passed, restarting them to make sure the issue is gone

**Comment by gorbak25** [comment]
@velzevur Could you restart them with instant mining? We could shave off a few seconds here ;)

**Review by gorbak25 — APPROVED** [review]

**Comment by gorbak25** [comment]
```
%%% aecore_txs_SUITE: Makefile:228: recipe for target 'ct-minerva' failed
make: *** [ct-minerva] Terminated
Makefile:431: recipe for target 'internal-ct' failed
make[1]: *** [internal-ct] Hangup

Too long with no output (exceeded 10m0s): context deadline exceeded
``` 
:thinking:

**Review by radrow — APPROVED** [review]

**Comment by velzevur** [comment]
It feels like I broke it even more now...

**Comment by gorbak25** [comment]
@velzevur try enabling deterministic mining and then find the hidden assumption in the test.
When I was fighting txs_gc the assumptions were:
1. You receive at least one block with a beneficiary different than us(otherwise GC won't kick in)
2. One specific generation needs at least 2 microblocks -.-

**Comment by velzevur** [comment]
So tests fail with
```
*** User 2021-02-17 15:37:37.844 ***
Transaction not received yet <<"th_2snpKf7ic5XGYygogQV6CXjmMscRawcEQgpCquNBbrM9Ukyd7o">>
```
where this is the hash of the last transaction. It was posted to `dev2` but it is unknown to it later on. _Investigating further more_

**Comment by velzevur** [comment]
I declare a partial success: it seems like the intensity of failing this test had dramatically decreased. I might have fixed _a few_ bugs there. Most prominent would be that the tx pool accepts txs which nonces are `Nonce =< AccountNonce + Offset`. This is not the case with new accounts, where the tx pool rejects all txs with nonce greater than `nonce_baseline` setting (1 by default). Hence providing a tx with a `nonce=5` on `dev2` can only succeed if it has seen a tx with a `nonce=1`. This is now fixed with bumping the setting `nonce_baseline`.

The tests still fail, but less often. I will investigate further more.

**Review by uwiger — APPROVED** [review]

**Comment by uwiger** [comment]
I'll take a partial improvement for now. :)

**Review by gorbak25 — APPROVED** [review]

**Pull request merged**
