### PR TITLE
Add different devcontainer configuration flavours

### PR DESCRIPTION
**Pull request by richcarl**
Replaces the single devcontainer specification file with three different ones (focal, jammy, and noble). VSCode will ask which one you want to use, so you can easily switch between building and running on Ubuntu 20, 22, or 24.

### CODE REVIEW

**Comment by dincho** [comment]
Not sure how this ended up in the codebase, but I'm definitely against cluttering the repository with personal configuration files. I won't block this one as I already missed my chance in the original PR, but won't approve it either.

**Review by dincho — COMMENTED** [review]
Not sure how this ended up in the codebase, but I'm definitely against cluttering the repository with personal configuration files. I won't block this one as I already missed my chance in the original PR, but won't approve it either.

**Comment by richcarl** [comment]
> Not sure how this ended up in the codebase, but I'm definitely against cluttering the repository with personal configuration files. I won't block this one as I already missed my chance in the original PR, but won't approve it either.

It's not intended as personal configuration, but to make it trivial for developers to run things in the same environment as the officially supported Aeternity docker environment, regardless of their local OS setup. If it works in the dev container, it should work in CI as well.

**Comment by dincho** [comment]
> > Not sure how this ended up in the codebase, but I'm definitely against cluttering the repository with personal configuration files. I won't block this one as I already missed my chance in the original PR, but won't approve it either.
> 
> It's not intended as personal configuration, but to make it trivial for developers to run things in the same environment as the officially supported Aeternity docker environment, regardless of their local OS setup. If it works in the dev container, it should work in CI as well.

As long as not the whole team is using it, it's personal in my book.

**Review by happi — APPROVED** [review]

**Review by klercker — APPROVED** [review]

**Pull request merged**
