### PR TITLE
Limit body request length

### PR DESCRIPTION
**Pull request by jyeshe**
- Allows setting request body limit by the Mdw (default is 1MB)
- It would be a safer call to set a lower limit to the Node as well but as requested this depends on monitoring how the `/dry-run` have been used so the config value is kept to the one default to cowboy.

### CODE REVIEW

**Review by sborrazas — APPROVED** [review]

**Comment by dincho** [comment]
What's the actual max body limit ?

**Comment by jyeshe** [comment]
> What's the actual max body limit ? Perhaps I don't fully understand this option, can you elaborate a bit more than the couple sentences in the docs ?

It stops reading from the socket and closes it when the body is bigger than the config value. As discussed in the meeting, the cowboy default value will be kept since the dry run accepts multiple txs until it's better known how the dry run is actually been used.

**Review by dincho — CHANGES_REQUESTED** [review]
config schema and epoch_full.yml also needs the corresponding updates

**Review by dincho — DISMISSED** [review]

**Comment by velzevur** [comment]
For every user visible change we add a markdown file in `docs/release-notes/next` (ex `docs/release-notes/next/limit_body_req_lenght.md`) that describes the change. When we do a release, we gather (and delete) all those files and put all collected change notes in the release notes. Please check #4093 for more details.

Please add a release notes line :)

**Review by velzevur — APPROVED** [review]

**Review by dincho — APPROVED** [review]

**Pull request merged**
