### PR TITLE
Update sdk in sdk_smoke_test to 13.3.2

### PR DESCRIPTION
**Pull request by davidyuk**
This PR is supported by the Æternity Foundation

https://hub.docker.com/r/circleci/node

### CODE REVIEW

**Comment by davidyuk** [comment]
Is there a way to make node produce some blocks? JS tests stuck on waiting the first block 🙁

**Comment by hanssv** [comment]
@davidyuk I don't know the setup here? How is the node configured? Is it mining? What difficulty? 

Why is the node waiting for a block, the test only seems to check if a preset account is funded or not 🤔

**Comment by davidyuk** [comment]
Ok, lets check only the account balance as before

**Comment by hanssv** [comment]
> Ok, lets check only the account balance as before

Ah, my bad, I only saw the waitForHeight, not the spend... I'm sure you could get the node to mine if you want a more excessive test, but let's make that in a separate PR.

**Review by hanssv — APPROVED** [review]

**Review by ThomasArts — APPROVED** [review]

**Pull request merged**
