### PR TITLE
Cleanup get state hc election

### PR DESCRIPTION
**Pull request by ThomasArts**
This PR is supported by Æternity Foundation.

### CODE REVIEW

**Review by klercker — APPROVED** [review]

**Comment by hanssv** [comment]
@dincho is not relying on this endpoint?

**Review by hanssv — COMMENTED** [review]
If it is always `?GENESIS_HEIGHT + 1` then maybe _both_ the name _and_ the value of the macro are wrong?

**Comment by ThomasArts** [comment]
The name is then wrong.
Long story short, GENESIS_HEIGHT was 5 before. But contract HCElection is now written in a way that it can only kick in on Height 0 when computing the initial epochs.

So, I use GENESIS_HEIGHT to start the chain and then can only use it from height 1.

**Comment by happi** [comment]
We should devise a (good) name for the "start" block. We have Genesis and then the first "live" block, which is perhaps just block one or the first block (following block 0 ;) ).

**Comment by ThomasArts** [comment]
But these tests do not really depend on running in the start block or first block, they just need a height larger than 0.
I am happy to fiddle with a new name, but I would go for `HEIGHT_ABOVE_GENESIS` or so and define that to be 1.

**Comment by happi** [comment]
It was a bit more philosophiocal idea. For these test I am fine with Genesis + 1. I was thinking of the whitepaper and the rest of the code.

**Comment by hanssv** [comment]
I'm thinking that `GENESIS_HEIGHT` and `HEIGHT` might be good constants in this case.

**Review by happi — DISMISSED** [review]
I approve;  you can merge at your discretion.

**Review by hanssv — DISMISSED** [review]

**Review by klercker — APPROVED** [review]
No merge until #4441 is in. PLEEEEEEAASE? 🥹

**Review by hanssv — APPROVED** [review]

**Review by happi — APPROVED** [review]

**Pull request merged**
