### PR TITLE
GH 2932 Fix test issues

### LINKED ISSUE #2932: %%% aesc_fsm_SUITE ==> {{badmatch,[{key_block,{key_header
## Expected Behavior
mine blocks functionality

## Actual Behavior
tests fail

## Logs, error output, etc.
https://circleci.com/gh/aeternity/aeternity/93542

https://circleci.com/gh/aeternity/aeternity/93532

### PR DESCRIPTION
**Pull request by velzevur**
Hopefully fixes #2932

### CODE REVIEW

**Comment by tolbrino** [comment]
Wouldn't this just crash now instead of proceeding?

**Comment by velzevur** [comment]
@tolbrino this would crash only if we are mining in a parallel, which would be an erronous test anyway

**Comment by tolbrino** [comment]
Then how does that improve anything?

**Comment by velzevur** [comment]
The process that is responsible for mining is the `aec_conductor`. Its mining state can be `running` or `stopped`. We start the mining with `aec_conductor:start_mining/0` and stop it with `aec_conductor:stop_mining/0`. When a new block is mined, the subscribed processes receive a `{gproc_ps_event, block_created | micro_block_created, Info}` that informs them a new block had been mined.

The test setup is counting the received `{gproc_ps_event, block_created | micro_block_created, Info}` messages and then calls the `aec_conductor:stop_mining/0`. There is a small chance that, because of fast mining setup, a block is mined before the stop message is actually processed by the `aec_conductor` process. In this case the mining is indeed stopped but the test process receives an unexpected `{gproc_ps_event, block_created | micro_block_created, Info}` message in its message queue. Later on we try flushing and assertively check that no blocks were mined while flushing. This assertion fails if we have a hanging message in the queue.

The changes in this PR lower the assertion that there was no message in the queue. They also make sure that there are no parallel mining attempts, which is intended to keep the same level of safety, so no lowering

**Pull request merged**
