### PR TITLE
GH 3501: aecore txs failures

### LINKED ISSUE #3501: Random CI failure in aecore_txs_SUITE:missing_tx_gossip
```
%%% aecore_txs_SUITE ==> missing_tx_gossip: FAILED
%%% aecore_txs_SUITE ==> {max_reached,
    [{aecore_suite_utils,mine_safe_setup,4,
         [{file,
              "/home/builder/aeternity/apps/aecore/test/aecore_suite_utils.erl"},
          {line,1391}]},
     {aecore_txs_SUITE,missing_tx_gossip,1,
         [{file,
              "/home/builder/aeternity/apps/aecore/test/aecore_txs_SUITE.erl"},
          {line,233}]},
     {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
     {test_server,run_test_case_eval1,6,
         [{file,"test_server.erl"},{line,1263}]},
     {test_server,run_test_case_eval,9,
         [{file,"test_server.erl"},{line,1195}]}]}
```

### PR DESCRIPTION
**Pull request by velzevur**
Fixes #3501

### CODE REVIEW

**Review by uwiger — DISMISSED** [review]

**Comment by velzevur** [comment]
```

%%% aecore_sync_SUITE ==> all_nodes.one_blocked.start_blocked_second: FAILED
%%% aecore_sync_SUITE ==> {{top_blocks_differ,[aeternity_dev1@localhost,aeternity_dev2@localhost]},
 [{aecore_sync_SUITE,expect_same_top,2,
                     [{file,"/home/builder/aeternity/apps/aecore/test/aecore_sync_SUITE.erl"},
                      {line,725}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
```
is unrelated to this fix

**Comment by velzevur** [comment]
The error being fixed did not show up, I restarted all tests to make sure :)

**Comment by velzevur** [comment]
```
%%% aehttp_sc_SUITE ==> plain.both_sign.conflicts.sc_ws_conflict_withdrawal_and_offchain_update: FAILED
%%% aehttp_sc_SUITE ==> {{connection_died,normal},
 [{aehttp_ws_test_utils,wait_for_msg,5,
                        [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_ws_test_utils.erl"},
                         {line,321}]},
  {aehttp_sc_SUITE,wait_for_channel_event_,3,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,4307}]},
  {aehttp_sc_SUITE,wait_for_channel_event_match,4,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,4281}]},
  {aehttp_sc_SUITE,'-sc_ws_conflict_/3-fun-0-',10,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,3557}]},
  {aehttp_sc_SUITE,channel_conflict,5,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,1060}]},
  {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
  {aehttp_sc_SUITE,sc_ws_conflict_,3,
                   [{file,"/home/builder/aeternity/apps/aehttp/test/aehttp_sc_SUITE.erl"},
                    {line,3560}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]}]}
```
unrelated failure

**Review by hanssv — APPROVED** [review]
Dimitar told me to hit approve :-)

**Review by uwiger — APPROVED** [review]

**Review by radrow — APPROVED** [review]

**Pull request merged**
