### PR TITLE
Prepare for OTP-27

### PR DESCRIPTION
**Pull request by hanssv**
Apart from 'else' and 'maybe' it was mainly deps with warning/errors/deprecations that needed update.

Also included a new rebar3.

This PR is supported by Æternity Foundation.

### CODE REVIEW

**Comment by hanssv** [comment]
Made this a drafs awaiting final versions of some repo updates and full sync tests on testnet/mainnet

**Review by ThomasArts — DISMISSED** [review]

**Review by mitchelli — DISMISSED** [review]

**Comment by hanssv** [comment]
Rebased - because of conflict...

**Review by ThomasArts — APPROVED** [review]

**Review by dincho — CHANGES_REQUESTED** [review]
You can't simply remove rebar3 :)

That would break:
- Makefile
- Dockerfile
- CI 

I'll try to find more specifics and eventual push fixes for that

**Review by dincho — APPROVED** [review]
Ah, I got confused by the UI, it's not removed but updated.

**Comment by hanssv** [comment]
Yes the old one was broken for both OTP-26 and OTP-27...

**Pull request merged**
