### PR TITLE
Add TCP connection check of unverified peers

### LINKED ISSUE #3134: Add TCP connection check of unverified peers
The node has issue finding peers that are alive in unverified pool and connect to them since there can be too many dead peers. Periodic TCP checks of random unverified peers could be helpful since the peers that can be connected to are moved to the verified pool. When a connection is going to be established, these available verified peers are selected first (not some random and most likely dead peers).

### PR DESCRIPTION
**Pull request by jur0**
Closes #3134

### CODE REVIEW

**Comment by dincho** [comment]
I wonder why TCP check and not full Noise check?

I see that tcp checked peers are added to the verified pool, so now it mixes peers that are know to accept Noise, and also peers that accept TCP but may not accept Noise or are part of other network ... this sounds very weird to me. It invalidate the metrics and we don't know anymore how many verified peers that accept Noise we have in the pool. If it's decided to keep this implementation at all, please also fix the metrics.

**Comment by jur0** [comment]
Full Noise connection is more expensive than just TCP. This is meant just to quickly check if a peer is alive.

**Comment by dincho** [comment]
> Full Noise connection is more expensive than just TCP. This is meant just to quickly check if a peer is alive.

Do you have numbers, how much more expensive ?

**Comment by jur0** [comment]
> > Full Noise connection is more expensive than just TCP. This is meant just to quickly check if a peer is alive.
> 
> Do you have numbers, how much more expensive ?

I don't, but if I was an attacker and wanted to fake live nodes, it's expensive to spin these nodes and it's pretty cheap to make the nodes accept Noise on the top of TCP. The difference between TCP and Noise check is negligible I'd say. The expensive part is to have an IP which is alive (in terms of TCP).

**Comment by hanssv** [comment]
The scenario where it would probably make a difference is when a node from the wrong network accidentally gets into a pool... But otherwise I agree with Juraj's assessment.

**Pull request merged**
