### PR TITLE
GH3013: Upgrade swagger to OAS3

### PR DESCRIPTION
**Pull request by velzevur**
This is partially implementing #3013: it upgrades the swagger definition to
OAS3 but in a backwards compatible way. There is more work to be done in order
to take advantage of it.

The work on this PR is being supported by ACF.

### CODE REVIEW

**Comment by velzevur** [comment]
JS tests fail with:
```

      path: '/:3013undefined/status',
      method: 'GET',
```
Apparently, they miss the `/v2` part that usually lives in swagger's `baseUrl`. This of course is gone in swagger version 3... Providing a fix.

**Comment by velzevur** [comment]
The JS-SDK is using the swagger definition to find proper types. It has the [hardcoded expectation of those living under `definitions`](https://github.com/aeternity/aepp-sdk-js/blob/develop/es/utils/swagger.js#L53). This is true for swagger2 but not true for openapi 3.

**Comment by velzevur** [comment]
I am testing a Python generated client. This is rather simple:
### Python OAS3 client
```

curl -X POST \
  https://generator3.swagger.io/api/generate \
  -H 'content-type: application/json' \
  -d '{
  "specURL" : "https://raw.githubusercontent.com/aeternity/aeternity/178601279a1d8b6dc3d35933de047886a52886d7/apps/aehttp/priv/oas3.yaml",
  "lang" : "python",
  "type" : "CLIENT",
  "codegenVersion" : "V3"
}' -o py.zip
```
and then you unzip the `py.zip`; I used a venv there and that the installation is as simple as:
```
python setup.py install --user 
```
This is defined in the generated README.md

Then we need to setup the config to point to the main net server. That would be `swagger_client/configuration.py`:
```
    def __init__(self):
        """Constructor"""
        # Default Base url
        self.host = "https://mainnet.aeternity.io/v2"
```

I will lists tests below

**Comment by velzevur** [comment]
Fetch a micro block by hash (this has a bunch of transactions in it):
```
$ cat t.py                                                                                                         [11:56:48]
from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# create an instance of the API class
api_instance = swagger_client.ExternalApi()
hash = 'mh_2i4jczGpXbhSxtc1WKDpDTu6XfFKXyzFMEAnCRffvZ3z5fmqVW' # str | The hash of the block

try:
    api_response = api_instance.get_micro_block_transactions_by_hash(hash)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling ExternalApi->get_micro_block_transactions_by_hash: %s\n" % e)
```

```
$ python t.py                                                                                                      [12:00:09]
{'transactions': [{'block_hash': 'mh_2i4jczGpXbhSxtc1WKDpDTu6XfFKXyzFMEAnCRffvZ3z5fmqVW',
                   'block_height': 391213,
                   'hash': 'th_rMDoiA6aZYECtxLAhWZRmYDsLbuHsjPXt38ncKShfyJ7eDuhb',
                   'signatures': ['sg_XLUu8bcEFJuKG9692atD6Z887g5xa3GnqxgX5C2SisWdbnd4wjrjxDv4B5cj75mYGfXSP8oNA93qwvN2BpmRpqW1LCWsB'],
                   'tx': {'amount': 20000,
                          'fee': 19320000000000,
                          'nonce': 4192524,
                          'payload': 'ba_MzkxMjEyOmtoX21aYkhoUE1ocWl6S2cyZnBHUUdxR0RkUEFuSzNBZEtIc1l4N3Vqd0xObWc5QnI0Nms6bWhfMm9IUVRWRG1RdXN5MzV6RGFyRld6eHRoY3FxanFqV3lhdnZzRlo4UG5ZbnZNQVdOTUg6MTYxNDE1NzY3OANVAIE=',
                          'recipient_id': 'ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs',
                          'sender_id': 'ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs',
                          'ttl': 391222,
                          'type': 'SpendTx',
                          'version': 1}},
                  {'block_hash': 'mh_2i4jczGpXbhSxtc1WKDpDTu6XfFKXyzFMEAnCRffvZ3z5fmqVW',
                   'block_height': 391213,
                   'hash': 'th_2N6QMtA1GczZWEBQ6ZWLoQyb4Yyw4muXaJgKt5JQF3A1GWDBye',
                   'signatures': ['sg_XEKrd8h6AcTaCoHz397Z9vyexB1vor6BBGWNoF6QJYFRZzB3kFDob7yLVeJZ7z61Q9VGRcJZyA84326F85k9DR3gntpVE'],
                   'tx': {'amount': 20000,
                          'fee': 19300000000000,
                          'nonce': 4192525,
                          'payload': 'ba_MzkxMjEyOmtoX21aYkhoUE1ocWl6S2cyZnBHUUdxR0RkUEFuSzNBZEtIc1l4N3Vqd0xObWc5QnI0Nms6bWhfTFZhQkV0WEJEdGhUUVlYNVdkSzRRMm9oQlpGZTRmWjhUUVdBdHY3Wnc1U25uaWladjoxNjE0MTU3Njg4yuozxA==',
                          'recipient_id': 'ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs',
                          'sender_id': 'ak_KHfXhF2J6VBt3sUgFygdbpEkWi6AKBkr9jNKUCHbpwwagzHUs',
                          'ttl': 391222,
                          'type': 'SpendTx',
                          'version': 1}},
                  {'block_hash': 'mh_2i4jczGpXbhSxtc1WKDpDTu6XfFKXyzFMEAnCRffvZ3z5fmqVW',
                   'block_height': 391213,
                   'hash': 'th_6kuDwAYnMUVAs6LDn5n45WR9NAxA838A9J45f3NPapnaGe3RX',
                   'signatures': ['sg_JeUKcjr6mzegrjeHEThYag72kYDM5MocBC5x5AZWvZTYApNeneyvc5esERWL1thbf1eQ2M6R2ghzy4fGG9xo8c9q2YHeM'],
```

**Comment by velzevur** [comment]
Fetching a transaction by a hash works great (a contract create one):
```
cat t.py                                                                                                       
from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# create an instance of the API class
api_instance = swagger_client.ExternalApi()
hash = 'th_2YbMcJDC1WiMCBP78eTiksZpbVmdBV2fmKWpZGJhaWJgHspcX9' # str | The hash of the transaction

try:
    api_response = api_instance.get_transaction_by_hash(hash)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling ExternalApi->get_transaction_by_hash: %s\n" % e)
```
$ python t.py                                                                                           
{'block_hash': 'mh_2tJ1844SSWoxwWt6PamaXM8X3h4J7o8nw9J9XTFFCKK2AXAvLH',
 'block_height': 390414,
 'hash': 'th_2YbMcJDC1WiMCBP78eTiksZpbVmdBV2fmKWpZGJhaWJgHspcX9',
 'signatures': ['sg_9Tns3Q7fHHooaK3j9gjkawMR4TArHaNzD9ZsjygFpqPDrieMWkLjrh1snfuV39xkyrfa4SvZ4gPBsN65k8byM4B7zdc1J'],
 'tx': {'abi_version': 3,
        'amount': 0,
        'call_data': 'cb_KxFE1kQfO0spQmVzdCBmcnVpdClCQU5BTkEhISEhARpodHRwczovL2VuLndpa2lwZWRpYS5vcmcvd2lraS9CYW5hbmEjL21lZGlhL0ZpbGU6QmFuYW5hX2FuZF9jcm9zc19zZWN0aW9uLmpwZ6+CAAEAPy8CABlCYW5hbmECEfCfjYyvggABARtvgwZnFShlSsY=',
        'code': 'cb_+QOxRgOgsXojRd7pqWnOkIV1AGwhycvEbshgiNMMNbalYQqEdKLAuQODuQKy/gg74mAANwEHNwACAxHw6nidJgAHDAb7A01QT0xMX0FMUkVBRFlfQ0xPU0VEKCwCgi8QAAcMCvsDVVZPVEVfT1BUSU9OX05PVF9LTk9XTiguBgiCVQAtSAYAKS6CCIJeAFUADAEARPwjBgQABgQDEWWl4A/+LZiGGwA3AHcoLACCKAwAAP49HoloADcANwY3BHd3d4cCNwA3AZdAZwd3hwI3ADcBBwdnRwAHRwABAoL+RNZEHwA3AzcEd3d3hwI3ADcBl0BnB3eHAjcANwEHNwAoHAAAPgAhMGQHDAT7A1FUSVRMRV9TVFJJTkdfVE9fTE9ORygcAgA+ACEwb4HsBwwI+wNpREVTQ1JJUFRJT05fU1RSSU5HX1RPX0xPTkcMAQAMAQIMAQRZACoAVQAnDAwPAoIBAz/+TZwYHwA3AUcAhwI3ADcBByguAAiCLxgAAAcMBET8IwACAAAAKxgAAET8IwACAgIA/lvZZvEANwBnRwAHKCwIggD+Y5TpegA3ADcEd3d3hwI3ADcBl0AoLACCAP5lpeAPAjcBhwI3A0cARwAHNwJHAEcANwAIPQACBEY2AAAARjYCAAJGNgQABGQCr1+fAYEHkNMuGeqn29s3+oEOHy2Z1zttuj24ZW78N3tricolWQACBAEDP0Y2AAAARjYCAAJjr1+fAYG3/lSR0tVIoIgx9DHEN4FlPcTOGFNNQbiv/iPdiBl9cAACAQM//onUrTcANwA3AFUAKCwIgi4AKS6CCIJeAFUARPwjBgQCBAQDEWWl4A/+sD4xsAA3AUcAFygsCIIvEAAA/rhCgMAANwFHABcoLAqCIBAAAP7J9p+dADcAhwI3ADcBBygsBIIA/uxtQeEANwAHAQMC/vDqeJ0ANwAXKC4ABIIIPgACBAEDf0Y6AgAAWQAiIAIAuMkvDhEIO+JgEXZvdGURLZiGGxV0aXRsZRE9HoloJWdldF9zdGF0ZRFE1kQfEWluaXQRTZwYHzF2b3RlZF9vcHRpb24RW9lm8RV2b3RlcxFjlOl6IW1ldGFkYXRhEWWl4A8tQ2hhaW4uZXZlbnQRidStNy1yZXZva2Vfdm90ZRGwPjGwJWhhc192b3RlZBG4QoDAJWlzX2F1dGhvchHJ9p+dMWNsb3NlX2hlaWdodBHsbUHhHXZlcnNpb24R8Op4nSVpc19jbG9zZWSCLwCFNC4xLjAAtc//BA==',
        'deposit': 0,
        'fee': 98160000000000,
        'gas': 1579000,
        'gas_price': 1000000000,
        'nonce': 7,
        'owner_id': 'ak_zXsfJ4LzJXwuBgdc7C2JdmdGedmiQVewrzmxdM8tV65QzYiYj',
        'type': 'ContractCreateTx',
        'version': 1,
        'vm_version': 5}}
```

**Comment by velzevur** [comment]
So this looks good now. It is mostly backwards compatible with the exception of `/headers/top` change. The biggest change is having proper a `Tx` type that allows generating proper swagger generated modules

**Comment by gorbak25** [comment]
@davidyuk Could you get involved in this PR? There will be more PR's with backwards incompatible changes after this one.

**Comment by velzevur** [comment]
@davidyuk bear in mind that the `big-int-as-string` will be introduced in a different PR

**Review by gorbak25 — APPROVED** [review]

**Comment by gorbak25** [comment]
@velzevur Does it make sense to run the entire integration suite under different protocols? Perhaps we shall dig into shaving off testing time this way?

**Comment by velzevur** [comment]
> @velzevur Does it make sense to run the entire integration suite under different protocols? Perhaps we shall dig into shaving off testing time this way?

With the exception of some protocol specific stuff, no we could be fine without being ran on different protocols

**Review by uwiger — APPROVED** [review]

**Pull request merged**
