### PR TITLE
Added DIR (--dir) option to ct-latest target

### PR DESCRIPTION
**Pull request by klercker**
Added `DIR=...` option to `ct-latest` make target. Allows you to run all test in a particular directory/ies.

Supported by  Aeternity Foundation

### CODE REVIEW

**Comment by kvakvs** [comment]
Remember to also update the Wiki https://github.com/aeternity/aeternity/wiki/Integration-Testing

**Comment by klercker** [comment]
Failed, funnily enough in the HC-involved parts of aehttp_stake_contract_SUITE.erl. Not much I can do about this, building off master with no changes to anything related to really anything in the tests...

**Comment by klercker** [comment]
Will update wiki once someone x2 approves the PR ;) Can you tie a wiki edit to a PR somehow? Would be pretty cool.

**Comment by dincho** [comment]
> Can you tie a wiki edit to a PR somehow? Would be pretty cool.

You can clone `git@github.com:aeternity/aeternity.wiki.git` edit and push it, but there are PRs on that repo

**Comment by hanssv** [comment]
> Failed, funnily enough in the HC-involved parts of aehttp_stake_contract_SUITE.erl. Not much I can do about this, building off master with no changes to anything related to really anything in the tests...

Well... It is possible to _fix_ intermittently failing test cases (and avoid introducing new ones) 😅

**Review by dincho — APPROVED** [review]

**Pull request merged**
