### PR TITLE
load plugin deps

### PR DESCRIPTION
**Pull request by uwiger**
This change detects application dependencies in plugin apps, and loads them automatically, given the assumption that they will reside under the same lib dir as the plugin app itself. This will be true for any plugin built with rebar3.

### CODE REVIEW

**Comment by nikita-fuchs** [comment]
Trying to test this by:

1. removing devmode-related deps from the node
2. adding them to the devmode plugin, where they look as follows:
```
{deps, [
        lager,
        cowboy,
        aeserialization,
        jsx,
        {ebip39,           
                {git, "https://github.com/aeternity/ebip39.git", {ref, "7520340"}}},
        {eaex10,
                {git, "https://github.com/aeternity/eaex10.git", {ref, "958046a"}}},
        {epbkdf2, 
                {git, "https://github.com/aeternity/epbkdf2", {tag, "v1.0.0"}}},
        {ec_utils,
                {git, "https://github.com/hanssv/ec_utils.git", {ref, "e557b1c"}}}
       ]}.
```

3. `rebar3 compile` the devmode and `make prod-build` the node.
4. Seeing in console: `[info] Trying to patch unknowns: []` 

What could I be doing wrong here ?

**Comment by uwiger** [comment]
> What could I be doing wrong here ?

Assuming you have compiled your plugin using rebar3, and have the compiled code in `<PLUGIN>/_build/default/lib/`, you could place a symlink in `<AE>/_build/prod/rel/aeternity/plugins/` pointing to `<PLUGIN>/_build/default/lib/<PLUGIN>`.

**Comment by nikita-fuchs** [comment]
Thanks, the issue was that I've placed the plugins into the rebar.config, not the .app.src -> `applications` dependencies. It seems to be working fine now.

**Review by nikita-fuchs — APPROVED** [review]

**Review by seanhinde — APPROVED** [review]
LGTM

**Pull request merged**
