### PR TITLE
Add aec_db write throughput test

### PR DESCRIPTION
**Pull request by tolbrino**
Ref #2974 

I'd like to merge this test before functional changes regarding the linked issue in order to see performance overhead of any changes.

### CODE REVIEW

**Comment by tolbrino** [comment]
For reference these numbers are the result at https://circleci.com/gh/aeternity/aeternity/99362 :

```
Throughput testing results (in microseconds):

# of block inserted	= 100
Total runtime		= 5435

Min	= 34
Max	= 83
Mean	= 54
Mode	= 73
Range	= 49
Median	= 53
```

**Comment by dincho** [comment]
What's the benefit having this run for each build ? 🤔

**Comment by tolbrino** [comment]
> What's the benefit having this run for each build ? 🤔

I'd like to get at least a rough indication whether any change adds 100% overhead to database operations. Once can certainly do more extensive testing manually which is more geared towards a specific change, but this minor test is a good rough guide. We've done something similar in the state channels CT suite.

**Comment by dincho** [comment]
> I'd like to get at least a rough indication whether any change adds 100% overhead to database operations. Once can certainly do more extensive testing manually which is more geared towards a specific change, but this minor test is a good rough guide. We've done something similar in the state channels CT suite.

That's OK, but then let's add 100% time increase assert then, so that one can notice it at all :)

**Comment by tolbrino** [comment]
> 
> That's OK, but then let's add 100% time increase assert then, so that one can notice it at all :)

For that to work you'd need some form of stateful statistics store which you can query against to compare the current result. Would be nice, but out of scope.

**Comment by sennui** [comment]
I really like these kind of checks. Given that eunit_lima is not significantly longer I am all for it

**Comment by hanssv** [comment]
👍

**Comment by tolbrino** [comment]
@dincho I'll keep your feedback in mind as a feature request.

**Pull request merged**
