### PR TITLE
[PT-165087263] Fix compilation of lz4 on win32 using port_compiler

### PR DESCRIPTION
**Pull request by tolbrino**
The actual fix is in this upstream PR: https://github.com/szktty/erlang-lz4/pull/12

### CODE REVIEW

**Comment by tolbrino** [comment]
@lucafavatella Could you verify this on your macOS setup?

**Comment by dincho** [comment]
Is the upstream maintained ?

**Comment by tolbrino** [comment]
> Is the upstream maintained ?

We'll see. But that's why I forked the repo so that the reference points to the fork for now.

**Comment by tolbrino** [comment]
@dincho review needed

**Pull request merged**
