### PR TITLE
Linux Arm64 Docker support

### PR DESCRIPTION
**Pull request by thepiwo**
just a placeholder to remind of updating dependencies for arm64 support

### CODE REVIEW

**Comment by dincho** [comment]
@thepiwo I believe all related PRs has been merged already. Could you please bring this up-to-date (i.e. correct commit shas) and remove the docker stuff, I'm working in another branch to have it build in the CI and I'll account dockerfile changes there.

**Comment by thepiwo** [comment]
Thanks @dincho I can do that on Monday

**Comment by thepiwo** [comment]
@dincho this still need updating https://github.com/aeternity/ecrecover/pull/16

**Comment by thepiwo** [comment]
@dincho updated :)

**Review by dincho — APPROVED** [review]

**Review by hanssv — APPROVED** [review]

**Review by hanssv — DISMISSED** [review]

**Review by hanssv — DISMISSED** [review]

**Review by dincho — APPROVED** [review]

**Review by seanhinde — APPROVED** [review]
LGTM

**Review by hanssv — APPROVED** [review]

**Pull request merged**
