### PR TITLE
Fix running mining unit tests on their own

### PR DESCRIPTION
**Pull request by lucafavatella**
Delivers https://www.pivotaltracker.com/story/show/164698259

This PR aims at showing that now eunit test of aec_mining module fails, thanks to setup app env not leaked any longer.

TODO:
* [x] Re-check manually re-running `make eunit` (rather than specific eunit test module)

### CODE REVIEW

**Comment by lucafavatella** [comment]
I realized I had invoked eunit with single module, so there may be other module leaking. Checking.

**Comment by lucafavatella** [comment]
From https://circleci.com/gh/aeternity/aeternity/14477
```
  1) aec_mining_tests:mine_block_test_/0: Find a new block
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_mining_tests.erl:41:in `aec_mining_tests:-mine_block_test_/0-fun-2-/0`
     Output: 
     Output: 
  2) aec_mining_tests:mine_block_test_/0: Proof of work fails with no_solution
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_mining_tests.erl:62:in `aec_mining_tests:-mine_block_test_/0-fun-4-/0`
     Output: 
     Output: 
  3) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 1)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  4) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 2)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  5) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 3)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  6) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 4)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  7) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 5)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  8) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 6)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  9) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 7)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  10) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 8)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  11) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 9)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
  12) aec_target_tests:target_adj_test_/0: With constant PoW capacity the target will stabilize (seed = 10)
     {minerva_accounts_file_missing,"/home/builder/aeternity/data.aeternity_ct@localhost/aecore/.minerva/accounts_test.json"}
     %% /home/builder/aeternity/apps/aecore/test/aec_target_tests.erl:28:in `aec_target_tests:-target_adj_test_/0-fun-4-/1`
     Output: 
     Output: 
```

**Comment by lucafavatella** [comment]
On 237661b59
```
$ make eunit TEST=aec_mining
...
2 tests, 0 failures
```

**Comment by hanssv** [comment]
This adds a lot of noise?!

```
17:01:01.855 [debug] Lager installed handler error_logger_lager_h into error_logger
17:01:01.880 [debug] Supervisor lager_sup started gen_event:start_link({local,epoch_mining_lager_event}) at pid <0.3312.0>
17:01:01.880 [debug] Supervisor lager_sup started gen_event:start_link({local,epoch_metrics_lager_event}) at pid <0.3313.0>
17:01:01.880 [debug] Supervisor lager_sup started gen_event:start_link({local,aeminer_lager_event}) at pid <0.3314.0>
17:01:01.864 [debug] Lager installed handler lager_console_backend into epoch_sync_lager_event
17:01:01.880 [debug] Supervisor lager_sup started gen_event:start_link({local,epoch_sync_lager_event}) at pid <0.3315.0>
17:01:01.919 [debug] Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.3318.0>
17:01:01.929 [debug] Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.3319.0>
17:01:01.939 [debug] Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.3320.0>
17:01:01.939 [debug] Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0},{job_input,0},{job_run,0},{job_time,0},{job_error,0}]) at pid <0.3321.0>
17:01:02.011 [info] Application lager started on node aeternity_ct@localhost
17:01:02.051 [debug] Supervisor gproc_sup started gproc:start_link() at pid <0.3327.0>
17:01:02.059 [debug] Supervisor gproc_sup started gproc_monitor:start_link() at pid <0.3328.0>
17:01:02.066 [debug] Supervisor gproc_sup started gproc_bcast:start_link() at pid <0.3329.0>
17:01:02.075 [debug] Supervisor gproc_sup started gproc_pool:start_link() at pid <0.3330.0>
17:01:02.075 [info] Application gproc started on node aeternity_ct@localhost
17:01:02.123 [debug] Supervisor jobs_app started jobs_server:start_link() at pid <0.3335.0>
17:01:02.131 [debug] Supervisor kernel_safe_sup started timer:start_link() at pid <0.3337.0>
17:01:02.131 [debug] Supervisor jobs_app started jobs_sampler:start_link() at pid <0.3336.0>
17:01:02.131 [info] Application jobs started on node aeternity_ct@localhost
17:01:02.153 [info] Application hut started on node aeternity_ct@localhost
17:01:02.204 [debug] Supervisor setup_sup started setup_srv:start_link() at pid <0.3343.0>
17:01:02.224 [info] Setup running ...
17:01:02.237 [info] Directories verified. Res = ok
17:01:02.237 [info] Setup phase 100
17:01:02.241 [info] Searching for config file aeternity.{json,yaml} in directory /Users/hans/.aeternity/aeternity
17:01:02.241 [info] Searching for config file aeternity.{json,yaml} in directory /Users/hans/Quviq/Aeternity/aeternity
17:01:02.241 [info] Searching for config file epoch.{json,yaml} in directory /Users/hans/.epoch/epoch
17:01:02.241 [info] Searching for config file epoch.{json,yaml} in directory /Users/hans/Quviq/Aeternity/aeternity
17:01:02.241 [info] No config file specified; using default settings
17:01:02.241 [info] aeu_env:read_config()-> ok
17:01:02.241 [info] Setup finished processing hooks (Mode=normal)...
17:01:02.242 [info] Application setup started on node aeternity_ct@localhost
17:01:02.271 [info] Application bear started on node aeternity_ct@localhost
17:01:02.303 [debug] Supervisor folsom_sup started folsom_sample_slide_sup:start_link() at pid <0.3350.0>
17:01:02.313 [debug] Supervisor folsom_sup started folsom_meter_timer_server:start_link() at pid <0.3351.0>
17:01:02.322 [debug] Lager installed handler lager_backend_throttle into lager_event
17:01:02.324 [debug] Supervisor folsom_sup started folsom_metrics_histogram_ets:start_link() at pid <0.3352.0>
17:01:02.324 [info] Application folsom started on node aeternity_ct@localhost
17:01:02.337 [info] Application parse_trans started on node aeternity_ct@localhost
17:01:02.367 [debug] Supervisor exometer_core_sup started exometer_admin:start_link() at pid <0.3358.0>
17:01:02.376 [debug] Supervisor exometer_core_sup started exometer_cache:start_link() at pid <0.3359.0>
17:01:02.385 [debug] Supervisor exometer_core_sup started exometer_report:start_link() at pid <0.3360.0>
17:01:02.392 [debug] Supervisor exometer_core_sup started exometer_report_logger_sup:start_link() at pid <0.3361.0>
17:01:02.400 [debug] Supervisor exometer_core_sup started exometer_folsom_monitor:start_link() at pid <0.3362.0>
17:01:02.407 [debug] Supervisor exometer_core_sup started exometer_alias:start_link() at pid <0.3363.0>
17:01:02.408 [info] Starting reporters with []
17:01:02.408 [info] Application exometer_core started on node aeternity_ct@localhost
17:01:02.408 [info] Application aeutils started on node aeternity_ct@localhost
17:01:02.766 [debug] Supervisor mnesia_sup started mnesia_sup:start_event() at pid <0.3375.0>
17:01:02.793 [debug] Supervisor mnesia_sup started mnesia_ext_sup:start() at pid <0.3376.0>
17:01:02.823 [debug] Supervisor mnesia_kernel_sup started mnesia_monitor:start() at pid <0.3378.0>
17:01:02.850 [debug] Supervisor mnesia_kernel_sup started mnesia_subscr:start() at pid <0.3379.0>
17:01:02.904 [debug] Supervisor mnesia_kernel_sup started mnesia_locker:start() at pid <0.3380.0>
17:01:02.931 [debug] Supervisor mnesia_kernel_sup started mnesia_recover:start() at pid <0.3381.0>
17:01:03.073 [debug] Supervisor mnesia_kernel_sup started mnesia_tm:start() at pid <0.3382.0>
17:01:03.096 [debug] Supervisor mnesia_kernel_sup started mnesia_checkpoint_sup:start() at pid <0.3383.0>
17:01:03.120 [debug] Supervisor mnesia_kernel_sup started mnesia_controller:start() at pid <0.3384.0>
17:01:03.168 [debug] Supervisor mnesia_kernel_sup started mnesia_late_loader:start() at pid <0.3385.0>
17:01:03.168 [debug] Supervisor mnesia_sup started mnesia_kernel_sup:start() at pid <0.3377.0>
17:01:03.169 [info] Application mnesia started on node aeternity_ct@localhost
17:01:03.512 [debug] init: GCHeight = 0
.17:01:03.819 [info] Application mnesia exited with reason: stopped
17:01:03.819 [info] Application aeutils exited with reason: stopped
17:01:03.819 [info] Application exometer_core exited with reason: stopped
17:01:03.819 [info] Application parse_trans exited with reason: stopped
17:01:03.819 [info] Application folsom exited with reason: stopped
17:01:03.819 [info] Application bear exited with reason: stopped
17:01:03.819 [info] Application setup exited with reason: stopped
17:01:03.819 [info] Application hut exited with reason: stopped
17:01:03.820 [info] Application jobs exited with reason: stopped
17:01:03.820 [info] Application gproc exited with reason: stopped
```

**Comment by lucafavatella** [comment]
I am taking the liberty of labelling as WIP as not planned for this release - so to ease filtering of open PRs.

**Comment by lucafavatella** [comment]
From integration test CI job https://circleci.com/gh/aeternity/aeternity/17038#tests/containers/1
```
%%% aecore_txs_SUITE ==> {max_reached,
    [{aecore_suite_utils,mine_blocks_until_txs_on_chain,4,
         [{file,
              "/home/builder/aeternity/apps/aecore/test/aecore_suite_utils.erl"},
          {line,279}]},
     {aecore_txs_SUITE,missing_tx_gossip,1,
         [{file,
              "/home/builder/aeternity/apps/aecore/test/aecore_txs_SUITE.erl"},
          {line,190}]},
```

**Comment by lucafavatella** [comment]
There were a couple of unrelated test failures on CI so I took the liberty of restarting CI.

**Comment by lucafavatella** [comment]
From integration CI job https://circleci.com/gh/aeternity/aeternity/17100#tests/containers/1
```
%%% aehttp_contracts_SUITE ==> contracts.maps_contract: FAILED
%%% aehttp_contracts_SUITE ==> {max_reached,
    [{aecore_suite_utils,mine_blocks_until_txs_on_chain,4,
         [{file,
              "/home/builder/aeternity/apps/aecore/test/aecore_suite_utils.erl"},
          {line,279}]},
     {aehttp_contracts_SUITE,force_fun_calls,1,
         [{file,
              "/home/builder/aeternity/apps/aehttp/test/aehttp_contracts_SUITE.erl"},
          {line,1280}]},
     {aehttp_contracts_SUITE,maps_contract,1,
         [{file,
              "/home/builder/aeternity/apps/aehttp/test/aehttp_contracts_SUITE.erl"},
          {line,644}]},
```
Seems unrelated, [already tracked](https://www.pivotaltracker.com/story/show/161653870/comments/201035742) and being looked into independently.

I consider not blocker for merging.

**Pull request merged**
