### PR TITLE
Add docs on testing and Rebar3

### PR DESCRIPTION
**Pull request by richcarl**
- hacking.md - reformatted to use headings instead of just bullets (lots of noise - sorry, but no real changes in this file).
- testing.md - brings in the text on Testing from the GitHub wiki pages ("where documentation goes to die").
- rebar.md - quick guide to Rebar3

### CODE REVIEW

**Review by klercker — APPROVED** [review]
good stuff

**Comment by kvakvs** [comment]
I had some situations where `rebar {something}` would fail because its counterpart `make {something}` had extra dependencies and extra build steps. Namely, i remember running ct via rebar was a problem, but works with Makefile. I.e. rebar and make targets with same name are not equivalent.

**Comment by ThomasArts** [comment]
Do we really advocate people to test via starting an Erlang shell and then manually starting applications... sounds to me like a very error prone and old fashion way of testing?

**Comment by richcarl** [comment]
> Do we really advocate people to test via starting an Erlang shell and then manually starting applications... sounds to me like a very error prone and old fashion way of testing?

I just collected the Testing stuff from the wiki. That particular part was written by yourself in 2017 :-) - should we drop it?

**Comment by hanssv** [comment]
Is it important for Hyperchains?

**Review by dincho — APPROVED** [review]
Finally the rebar magic documented in a single place :)

**Pull request merged**
